name: Renovate checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-renovate:
    name: Check Renovate files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: equisoft-actions/with-asdf-vm@v1
      - run: make check.renovate
